### ISSUE TITLE
Build!

### ISSUE THREAD

**Issue by mzmmohideen** [vinben/Rotopp#1]
I made a build for Ubuntu.. but that executable is not working in another ubuntu machine... throwing some dependencies error. how to get rid out from this

**Comment by vinben** [comment]
Unfortunately, our current version does not support the deployment. The general way for the deployment might build all the dependencies e.g. ceres, opencv and qt5 etc in STATIC before rebuilding our code. For more information on qt-related deployment, please see this:
http://doc.qt.io/qt-5/linux-deployment.html
